### ISSUE TITLE
Planning integration of the volunteer app w/ new API

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/hq#29]
Quick list of planning-related tasks:

* [x] Match up old API endpoints with equivalents
  * Determine payloads of old API endpoints
  * Determine mapping to payloads of new API endpoints
  * Document these
* [ ] ~~Can we estimate current number of users?~~
  * Use current traffic through volunteer endpoints to estimate
* [x] Determine sufficiency of current authentication mechanism @astroash
  * Does the app use an auth token?
  * Can it be simply integrated with our current JWT-based auth scheme?
* [ ] ~~Estimate work required to create proxy to support legacy app users~~
  * Depending on complexity, it may be preferable to simply break the old app and force users to upgrade.
* [x] Document process of building/testing app locally (and setting up local environment) @astroash

**Comment by astroash** [comment]
## Determine sufficiency of current authentication mechanism
### 📱 Twine-App
[🔗 to twine-app login controller](https://github.com/TwinePlatform/Twine-App/blob/0038dad2b78fb387a3bc10c8b169fde41492eb54/www/js/controllers/login-controller.js#L44-L56)

- twine-app is storing previous login details (email & password) in local storage for future logins under `lastAuth`
- on successful login it stores user details in local storage under `user` for other pages
_NB: app is currently checking `user.role_id` to find out if a user is an volunteer_admin or volunteer._
- for integration with the new api, a jwt can be stored local storageon login, then used to authenticate subsequent requests. This does not have to interfere with the current usage of for storing data. 


### 👩🏻‍💼 Twine-Admin
It's unclear whether/how the php app is authenticating requests from native app. There is a number of middleware files that are being imported however this just seems to be used for the server rendered app:

```
./app/Http/Controllers/Auth/AuthController.php
|
| _ ./vendor/laravel/framework/src/Illuminate/Foundation/
    Auth/AuthenticatesAndRegistersUsers.php
    |
    | _ AuthenticatesUsers.php
    |
    | _ RegistersUsers.php
```

**Comment by astroash** [comment]
## Document process of building/testing app locally 
### 🏃  running locally
```bash
> cd Twine-App
> npm i -g cordova ionic gulp
> npm i
> ionic build
npm ERR! 404 Not Found: ansi-styles@2.2.0
😢
> rm -rf node_modules
> rm -rf package-lock.json
> npm i
> ionic build
Cannot run sass task: missing in gulpfile.js
(uhhh ooo)
> ionic serve
👌🏽

```

**Comment by eliascodes** [comment]
After discussion we decided not to invest in supporting legacy app users for reasons I won't go into here.
